services:
  postgres_resantuario_db:
    image: postgres
    container_name: postgres_resantuario_db
    restart: always
    ports:
      - 4457:5432
    env_file:
      - .env.docker
    volumes: 
      - pg_resantuario-db:/var/lib/postgresql/data

  node_resantuario_app:
    container_name: node_resantuario_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - postgres_resantuario_db
    env_file:
      - .env.docker

volumes:
  pg_resantuario-db: