-- AlterTable
ALTER TABLE "ingredients" ALTER COLUMN "kCalPerG" DROP NOT NULL,
ALTER COLUMN "proteinPerG" DROP NOT NULL,
ALTER COLUMN "carbsPerG" DROP NOT NULL,
ALTER COLUMN "lipidPerG" DROP NOT NULL;
